# These are supported funding model platforms

github:  surajsahani
patreon: surajsahani
open_collective: # Replace with a single Open Collective username
ko_fi: surajsahani
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: surajsahani
otechie:  Suraj Sahani 
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: https://www.paypal.com/paypalme/surajkumarsahani1997
